### ISSUE TITLE
Remove daoSetter in KyberFeeHandler

### ISSUE THREAD

**Issue by manhlx3006** [KyberNetwork/katalyst_dao_sc#7]
Previously, KyberDAO has a record of KyberFeeHandler's address to help user claim reward, and it is only set once in constructor, thus, we need to have daoSetter to set KyberDAO's address in KyberFeeHandler.
However, with the new design, as KyberDAO is no long keep a record of KyberFeeHandler's address, it is not needed to have daoSetter in KyberFeeHandler anymore.

**Comment by ducquangkstn** [comment]
Moreinfo: https://github.com/KyberNetwork/kyber_dao_sc/blob/c83b7e92726a7af771f2ba41c9ca6273a32f7e47/contracts/KyberFeeHandler.sol#L335
